### ISSUE TITLE
Obtain local Lipschitz constant of a given network

### ISSUE THREAD

**Issue by yifei-liu-stat** [yjhuangcd/local-lipschitz#1]
Hello, 

It seems that this repo is mainly for training NN to restrict the upper bounds of local Lipschitz constants on a dataset. I am wondering is there a way to simply extract the local Lipschitz constant of a trained neural network for any given input? I might miss something from the repo, but any help would be much appreciated.

**Comment by huanzhang12** [comment]
I think it is possible. @yjhuangcd can you point out how to output local Lipschitz for a given model and point using our codebase?

@TrueRealEason There is one caveat: if a network is not trained using our method, the local Lipschitz bound computed by our method can be loose (e.g., not too much better than global Lipscthiz).

**Comment by yifei-liu-stat** [comment]
@huanzhang12 Sounds good, thank you! I have another question though. What if I use other robust training methods (not explicitly regularize Lip constants), will the local Lip constants be small compared to the global one? I am asking this question because I have read somewhere robust NNs usually have smaller global Lip constants compared to those trained in standard ways.

**Comment by huanzhang12** [comment]
I guess the answer is positive - usually robustly trained models tend to have tighter Lipschitz bound. But of course you will have to try it out to see if that is true for the models you have🙂️

**Comment by yjhuangcd** [comment]
Hi @TrueRealEason, thanks for your interest in our work! Yes you can compute the local Lipschitz bound of a trained neural network using the `robust_loss` function in [`Local_bound.py`.](https://github.com/yjhuangcd/local-lipschitz/blob/590e0ae4f98ed2b36aef49f0f6543dc1145f2704/Local_bound.py#L186) This function will output `r_prev`, which is the local Lipschitz bound until the second last layer of the neural network.

**Comment by yifei-liu-stat** [comment]
Hello @yjhuangcd are you talking about the forward pass below?
https://github.com/yjhuangcd/local-lipschitz/blob/590e0ae4f98ed2b36aef49f0f6543dc1145f2704/Local_bound.py#L187
In that case, what would `u_list` be initialized as? If I gave it `None` but I got AttributeError instead. I looked up the repo and didn't find the description of `u_list`. could you shed some light on it. Thanks.

**Comment by yifei-liu-stat** [comment]
By the way, here is what I used:
```python
...
# get local Lipschitz constant for each layer at each data point
u_list = None
_, _, r_prev, _, _, _, _, _, _ = net_local(X, 0.3, u_list, u_train_data, 10)
```
(a detailed one: https://github.com/TrueRealEason/test_localLip/blob/408fb75e60a31e40cf8748bbcbe2db5578984bfa/test_Lip.py#L1-L58)

and this is the error message I got:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.conda/envs/adversarial/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/<myprojectpath>/local-lipschitz/Local_bound.py", line 269, in forward
    self.Dn_mask[i] = self.Dn_mask[i-1].view(mu.size()[0], -1)
AttributeError: 'NoneType' object has no attribute 'view'
```
It seems that `Dn_mask[i-1]` is `None` initially, which causes trouble thereafter. Do you have any suggestions? @yjhuangcd Thanks.

**Comment by yjhuangcd** [comment]
Hi @TrueRealEason, if you run with `python test_lip.py --model relux`, that error will go away. The reason is that the code selects which interval bound propagation function to use based on the activation function (may be relu_{\theta} or maxmin). 

In addition, our code only supported relu_{\theta} or maxmin nonlinear activation previously. I have updated the code to also support standard relu, and you need to use `--model standrelu` for that. Hopefully this will make it more convenient to be used for evaluating the local Lipschitz bound of pretrained model.

**Comment by yifei-liu-stat** [comment]
thanks for the update!
